### ISSUE TITLE
runDiscoGen fails with NPE

### ISSUE THREAD

**Issue by DFrenkel** [googleapis/discovery-artifact-manager#155]
#### Environment details

  - OS: Linux
  - Java version: 
```
openjdk version "1.8.0_181-google-v7"
OpenJDK Runtime Environment (build 1.8.0_181-google-v7-313002728-313002728)
OpenJDK 64-Bit Server VM (build 25.181-b01, mixed mode)
```

#### Steps to reproduce

  1. You want to generate code samples for Cloud Billing (pick any service in scope) for the purpose of uploading them to be used by the Google Cloud Docs website, so you `cd toolkit` and run 
```
./gradlew runDiscoGen "-Pclargs=--discovery_doc=../discoveries/cloudbilling.v1.json,--gapic_yaml=./src/main/resources/com/google/api/codegen/py/python_gapic.yaml,--output=/tmp/docs/billing/"
```

#### Expected
Code samples for Cloud Billing are produced in `/tmp/docs/billing` and can be reviewed and uploaded

#### Actual
```
> Task :runDiscoGen
the generator class 'com.google.api.codegen.gapic.MainGapicProviderFactory' does not extend the expected class 'com.google.api.codegen.discovery.DiscoveryProviderFactory'Exception in thread "main" java.lang.NullPointerException
        at com.google.api.codegen.DiscoveryFragmentGeneratorApi.process(DiscoveryFragmentGeneratorApi.java:144)
        at com.google.api.codegen.DiscoveryFragmentGeneratorApi.run(DiscoveryFragmentGeneratorApi.java:194)
        at com.google.api.codegen.DiscoveryFragmentGeneratorTool.generate(DiscoveryFragmentGeneratorTool.java:113)
        at com.google.api.codegen.DiscoveryFragmentGeneratorTool.main(DiscoveryFragmentGeneratorTool.java:86)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runDiscoGen'.
> Process 'command '/usr/local/buildtools/java/jdk8-google-v7-64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 2s
```
```

**Comment by dazuma** [comment]
@vchudnov-g ^

**Comment by vchudnov-g** [comment]
We're no longer supporting automatic generation of samples from Discovery files. Samples for such API Client Libraries must now be modified or added manually.  Samples for the newer Google Cloud Client Libraries (GAPICs) are a different topic. I can provide more info internally.

**Comment by vchudnov-g** [comment]
Closing as per the comment above.
